/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fahrtenbuch;

import javax.swing.JTextField;

/**
 *
 * @author Max_2
 */
public class MainGui extends javax.swing.JFrame {

    private Fahrtenbuch myFahrt;

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        Fahrtenbuch myFahrt = new Fahrtenbuch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fahrtenbuch = new javax.swing.JLabel();
        setName = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        kommentar = new javax.swing.JLabel();
        setComment = new javax.swing.JTextField();
        Zeitraum = new javax.swing.JLabel();
        von = new javax.swing.JLabel();
        setStartDate = new javax.swing.JTextField();
        bis = new javax.swing.JLabel();
        setEndDate = new javax.swing.JTextField();
        FahrtenbuchAnlegen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fahrtenbuch.setText("Neues Fahrtenbuch anlegen");

        setName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameActionPerformed(evt);
            }
        });

        name.setText("Name:");

        kommentar.setText("Kommentar (optional):");

        setComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCommentActionPerformed(evt);
            }
        });

        Zeitraum.setText("Zeitraum");

        von.setText("von:");

        setStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStartDateActionPerformed(evt);
            }
        });

        bis.setText("bis:");

        setEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEndDateActionPerformed(evt);
            }
        });

        FahrtenbuchAnlegen.setText("Anlegen");
        FahrtenbuchAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FahrtenbuchAnlegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(name)
                        .addComponent(setName)
                        .addComponent(fahrtenbuch)
                        .addComponent(kommentar)
                        .addComponent(Zeitraum)
                        .addComponent(setComment)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(von)
                                .addComponent(bis)
                                .addComponent(setEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(setStartDate))))
                    .addComponent(FahrtenbuchAnlegen))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fahrtenbuch)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kommentar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Zeitraum)
                .addGap(4, 4, 4)
                .addComponent(von)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(FahrtenbuchAnlegen)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameActionPerformed
        this.myFahrt = new Fahrtenbuch();
        this.myFahrt.setName(setName.toString());
    }//GEN-LAST:event_setNameActionPerformed

    private void setCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCommentActionPerformed
        this.myFahrt.setKommentar(setComment.toString());    
			
	}//GEN-LAST:event_setCommentActionPerformed

    private void FahrtenbuchAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FahrtenbuchAnlegenActionPerformed
    
	myFahrt.
	
	}//GEN-LAST:event_FahrtenbuchAnlegenActionPerformed

    private void setStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setStartDateActionPerformed

    private void setEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setEndDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FahrtenbuchAnlegen;
    private javax.swing.JLabel Zeitraum;
    private javax.swing.JLabel bis;
    private javax.swing.JLabel fahrtenbuch;
    private javax.swing.JLabel kommentar;
    private javax.swing.JLabel name;
    private javax.swing.JTextField setComment;
    private javax.swing.JTextField setEndDate;
    private javax.swing.JTextField setName;
    private javax.swing.JTextField setStartDate;
    private javax.swing.JLabel von;
    // End of variables declaration//GEN-END:variables

    public JTextField getSetComment() {
        return setComment;
    }

    public JTextField getSetEndDate() {
        return setEndDate;
    }

    public JTextField getSetName() {
        return setName;
    }

    public JTextField getSetStartDate() {
        return setStartDate;
    }
}
